### ISSUE TITLE
HA integration asks for BT mac

### ISSUE THREAD

**Issue by Symbiot78** [8none1/idealLED#1]
Hi

just wondering what BT mac address the component is asking for? for the iDeal led strip (bought as BTF lightning leds) BT mac address or the HA server or?

I can't seem to find any mac address for BT in the iDeal app but am assuming it's for the lights.

I am using iOS.

**Comment by 8none1** [comment]
If you have LED devices which are supported by this integration they will show up in the Home assistant frontend without you having to enter a MAC address. 

That you are being asked to enter the MAC address of the LED device suggests that your lights are not supported.
