### ISSUE TITLE
new device IDL-1CA107 (A107)

### ISSUE THREAD

**Issue by fernac03** [8none1/idealLED#10]
this device work  but  i  need  to chage 
on idealled.py 
NAME_ARRAY = ["ISP-"]   to NAME_ARRAY = ["IDL-"]
and on config_flow.py 
return self._discovery.name.lower().startswith("isp-")
to 
 return self._discovery.name.lower().startswith("idl-")

only problem  is to turn off

**Comment by 8none1** [comment]
Nice work!

Before I go and add this new device, let's see if we can get off working.

What happens if you call the same bytes as `ON`?  Does that turn it off?

**Comment by fernac03** [comment]
hi ,
when I send turn on first time the LED lights up flashing, when I send turn off the LED stays on steadily.
and the same if I send turn on and turn on,

**Comment by 8none1** [comment]
Very strange.  The difference between an `ON` and an `OFF` in the commands is a `1` and a `0` in the bytes. 

I wonder why they would change the the power off command from a `0` to something else??

I'm OK with making the change to include the IDL devices but I would love to know why it's ignoring the `OFF` command.  Maybe it's a checksum thing?

Can you share a link to the lights you have and I will see if I can pick up a set in the UK.  Maybe AliExpress have them?

**Comment by fernac03** [comment]
https://a.aliexpress.com/_mt9Cz8f  i have this  2x2  i will  try change
off  value

Em ter., 19 de nov. de 2024, 12:21, Will Cooke ***@***.***>
escreveu:

**Comment by 8none1** [comment]
Ah yeah, that's a bit too pricey just for lolz.

Something you can try if you have an Android phone:

 - Enable Bluetooth debugging.  This varies from device to device.  A Google search will be required
 - Open the App
 - Turn the lights on and off 5 times or so
 - Close the app
 - Turn off debugging
 - Find the debug file and attach it to this image. 

I might be able to extract the Bluetooth commands from that and see what's going on

**Comment by fernac03** [comment]
this log ?

Em ter., 19 de nov. de 2024 às 13:04, Will Cooke ***@***.***>
escreveu:

**Comment by 8none1** [comment]
Maybe the attachment is missing?

The process is something like this:  https://medium.com/@charlie.d.anderson/how-to-get-the-bluetooth-host-controller-interface-logs-from-a-modern-android-phone-d23bde00b9fa

**Comment by fernac03** [comment]
[btsnoop_hci.log](https://github.com/user-attachments/files/17819052/btsnoop_hci.log)
i send by email git not accepted

**Comment by 8none1** [comment]
Extracted `btatt` values are:

```text
00a80cff618641cbb5c6b947af6674ed6d
010629b0a02c0da951d07bd89397ae69a7
0270617373
003647f7b1b6275fcedb527f9801b83f34
01a9ec7709aa61446934fea6a65d1e5997
0270617373
fedcbac0030006d3ffffffff00ef
fedcba0003003e00d30200200501000000000902590b4628c4fe0e0006040000004e0002050003080001020900020a00020601050d0080021c081100590b461ca107021300ef
cbb1fdbfc560d5e453c2cbd928b53fab
77efb2d528338f3a65329af385683aba
d55cd52aec5d61a93a441500b95ade4d
e578f45a6a4f00c26f0977f8f5430c87
608920f5645d6427f602e2d4d5865da5
50053c66f08235972cac2e201c81ccd2
c0178dbcdc2841fbad2a727c640242f8
8ebc70eb0de699d5eb16383e026d2ac6
cbb1fdbfc560d5e453c2cbd928b53fab
8ebc70eb0de699d5eb16383e026d2ac6
cbb1fdbfc560d5e453c2cbd928b53fab
8ebc70eb0de699d5eb16383e026d2ac6
cbb1fdbfc560d5e453c2cbd928b53fab
8ebc70eb0de699d5eb16383e026d2ac6
cbb1fdbfc560d5e453c2cbd928b53fab
8ebc70eb0de699d5eb16383e026d2ac6
cbb1fdbfc560d5e453c2cbd928b53fab
```

These now need to be decrypted and hopefully we find the answer....

**Comment by 8none1** [comment]
```text
~/source/idealLED/aes_decrypt.py ./encrypted 
00 A8 0C FF 61 86 41 CB B5 C6 B9 47 AF 66 74 ED 6D
01 06 29 B0 A0 2C 0D A9 51 D0 7B D8 93 97 AE 69 A7
02 70 61 73 73
00 36 47 F7 B1 B6 27 5F CE DB 52 7F 98 01 B8 3F 34
01 A9 EC 77 09 AA 61 44 69 34 FE A6 A6 5D 1E 59 97
02 70 61 73 73
FE DC BA C0 03 00 06 D3 FF FF FF FF 00 EF
FE DC BA 00 03 00 3E 00 D3 02 00 20 05 01 00 00 00 00 09 02 59 0B 46 28 C4 FE 0E 00 06 04 00 00 00 4E 00 02 05 00 03 08 00 01 02 09 00 02 0A 00 02 06 01 05 0D 00 80 02 1C 08 11 00 59 0B 46 1C A1 07 02 13 00 EF
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 77 EF B2 D5 28 33 8F 3A 65 32 9A F3 85 68 3A BA
Decrypted:       05 4C 45 44 53 00 00 00 00 00 00 00 00 00 00 00
Decimal:        05 76 69 68 83 00 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDS
Original string: D5 5C D5 2A EC 5D 61 A9 3A 44 15 00 B9 5A DE 4D
Decrypted:       08 54 49 4D 45 02 0E 0A 02 00 00 00 00 00 00 00
Decimal:        08 84 73 77 69 02 14 10 02 00 00 00 00 00 00 00
ASCII:         TIME

Original string: E5 78 F4 5A 6A 4F 00 C2 6F 09 77 F8 F5 43 0C 87
Decrypted:       04 53 54 53 43 00 00 00 00 00 00 00 00 00 00 00
Decimal:        04 83 84 83 67 00 00 00 00 00 00 00 00 00 00 00
ASCII:          STSC
Original string: 60 89 20 F5 64 5D 64 27 F6 02 E2 D4 D5 86 5D A5
Decrypted:       0C 53 54 53 43 00 7F 12 00 00 7F 05 04 00 00 00
Decimal:        12 83 84 83 67 00 127 18 00 00 127 05 04 00 00 00
ASCII:          
                STSC
Original string: 50 05 3C 66 F0 82 35 97 2C AC 2E 20 1C 81 CC D2
Decrypted:       06 53 54 49 4E 00 00 00 00 00 00 00 00 00 00 00
Decimal:        06 83 84 73 78 00 00 00 00 00 00 00 00 00 00 00
ASCII:          STIN
Original string: C0 17 8D BC DC 28 41 FB AD 2A 72 7C 64 02 42 F8
Decrypted:       05 53 54 49 4E 01 00 00 00 00 00 00 00 00 00 00
Decimal:        05 83 84 73 78 01 00 00 00 00 00 00 00 00 00 00
ASCII:          STIN
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
```

**Comment by 8none1** [comment]
So the result here is that it is indeed a new protocol.  It looks entirely new and totally different to the old one, but I guess they kept the old protocol (or at least some of it) around in the code.  And they didn't change the encryption key!

Is it *only* `OFF` that doesn't work?  i.e. can you change the colours etc?

While I work out what to do about this long term, you can in the short time fix your local version by:

 -     Find [this line](https://github.com/8none1/idealLED/blob/413330adf4e1d80848be1866dec8c7e21f63060b/custom_components/ideal_led/idealled.py#L365) in your local version
 - Change the `byteArray` to `06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00`
 - Remove the `packet[5]` line
 
And that should work.  Let me know how you get on.

**Comment by fernac03** [comment]
I modified the turn on and the turn off is now working perfectly, I will try to change the colors but I need to get home

**Comment by 8none1** [comment]
I'm closing this issue as we have some more debugging and some instructions for testing a new branch over here:

https://github.com/8none1/idealLED/issues/7#issuecomment-2536989978
