### ISSUE TITLE
(<class 'custom_components.ideal_led.light.IDEALLEDLight'>) does not report a color mode

### ISSUE THREAD

**Issue by aletzi1** [8none1/idealLED#12]
My log shows me sometimes this warning message:

light.isp_ac6c78_6c78 (<class 'custom_components.ideal_led.light.IDEALLEDLight'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/8none1/idealLED/issues

Do you need any more information to fix this?

**Comment by 8none1** [comment]
Thanks for the report.  I know what needs to be done to port this to the new requirements, just need to do it

**Comment by 8none1** [comment]
Seems like I don't know what needs to change, it's still moaning.  There are seemingly no docs on this.

**Comment by 8none1** [comment]
Ok, I think the latest version will at least silence that warning, but I don't really know if this is the correct fix or not.  This is poorly documented on the HA front.  I'll keep investigation, but for now this should be fixed.
