### ISSUE TITLE
Feature request: ability to set the effect speed

### ISSUE THREAD

**Issue by spupetic** [8none1/idealLED#3]
The effect speed can be set with the app, but not with the integration. I think it is an important feature, because some effect are really fast on the default setting.

**Comment by 8none1** [comment]
Home Assistant doesn't (afaik) have a good control to set the effect speed in the UI.  If you want to change the speed yourself to a new fixed number you can edit this line:

https://github.com/8none1/idealLED/blob/d88db98b7359694583a42b342b4e1cebc51d3164/custom_components/ideal_led/idealled.py#L284

**Comment by spupetic** [comment]
Thanks, but it would be much better to do this from the UI, therefore it is not necessary to make it a fixed value. WLED has this solution for the problem:
[](https://community.home-assistant.io/t/wled-expose-effect-speed-and-intensity-as-input-number-sliders/202065)
