### ISSUE TITLE
Performance setting all leds to a custom pattern

### ISSUE THREAD

**Issue by mas802** [8none1/idealLED#4]
Thanks for the great work, got me quickly started on working with these. Currently I am however stuck, since I want to set all led to a custom pattern, but updating them using the graffiti_paint method individually is taking 1.5 seconds. How does the app set a custom pattern over all lights, it seems to be much faster. I was not able to read this out of the material provided and to not have the tools and skills currently to dig through it myself. 

Any help or pointers appreciated. Keep up the good work.

**Comment by 8none1** [comment]
Hi @mas802 

When you say you want to set all the leds to a custom pattern, do you mean that you want to set all the pixels to the *same* pattern, or that you want to set a custom pattern which has a different setting for each pixel?

e.g. are you itterating through a list of individual pixels and setting each one in turn? 

I expect that is why it's slow; writing each pixel, waiting for the communication to complete, then moving on to the next pixel and so on.

It's been a while since I played with these lights, but looking at my notes it looks like it is possible to send a longer list of colours in one go which will almost certainly be faster.

What is your goal here, to set each pixel in the string to a specific colour?

**Comment by mas802** [comment]
Hi,

You got it right I would like to do custom animation on these lights (a sort of water flow effect, but with different length of strands). While I think I can get away with a low refresh rate, 30ms per pixel is just too slow.

**Comment by 8none1** [comment]
I see.  I don't know if it will be possible I'm afraid. 

It looks like you can send an array of bytes to the strip in one go, but that is very basic colour settings and an effect applied over the whole strip:

https://github.com/8none1/idealLED/blob/dea0cafacb428fb73cd150b755e4e30121fb1c58/idealled_controller.py#L269

Are you able to (nearly) do what you want in the app?  If so leave some instructions for how to recreate it in the app and I'll sniff the conversation and see if I can work out whats going on.

**Comment by mas802** [comment]
So here is why I think it should be possible (on the iOS App):

1. Open the DIY mode (palette symbol)
2. Switch at the bottom with the brush symbol to the matrix where you can set individual pixels
3. Save two different patterns using the heart symbol and give them a name
4. Back to the main screen and open the "Collect" Option (heart symbol)
5. Here you can switch between the patterns, which feels pretty instant to me.

So if that works on android as well, maybe you can sniff out what is going on if you have the time. Would be very nice to see if that is an option for my project.

**Comment by 8none1** [comment]
Ok, some progress, but not much.

The conversation looks like this:

```text

Decrypted:       04 44 4F 4F 54 01 00 00 00 00 00 00 00 00 00 00
<long series of bytes>
Decrypted:       06 44 4F 4F 54 43 50 00 00 00 00 00 00 00 00 00
Decrypted:       08 44 54 41 52 54 43 59 01 00 00 00 00 00 00 00
```

I think only the first command is needed to start sending the colours, but I don't know yet.  More experimentation is needed tomorrow. 

The long series of bytes is being truncated by Wireshark and I don't know how to fix that, but I can start to make a guess at what's going on.  This set 10 pixels to red, and then 10 pixels to white:

```text
16 00 00 0a ff 00 00 02 64 00 0a ff ff ff 02 64 00 50 00 00 00 02 64 00 00 00 00 00 00 00 00 00 00 00 00 00…
```


0a = 10 in decimal

So I think it means something like:
```text
|------| ---------------- ?
         || ------------- the next 0a (10) pixels are
         || ||-||-|| ---- RGB
         || || || || ||-- ?
         || || || || || ||- ? (100, could be brightness)
         || || || || || || || - ?
         || || || || || || || || - the next 0a (10) pixels are
         || || || || || || || || ||-||-||---- white
         || || || || || || || || || || || || || ||
                                                   || - 80 decimal
                                                      |------| - off
16 00 00 0a ff 00 00 02 64 00 0a ff ff ff 02 64 00 50 00 00 00 02 64 00 00 00 00 00 00 00 00 00 00 00 00 00…
```

There are 100 pixels on my lights, so 10 red plus 10 white plus 80 off = 100!

I think this means that the pixel data is:
```text
00, pixel count, rr, gg, bb, something, something
```

or perhaps the `00` goes at the end instead.

I would guess that the first two bytes are the payload length.  0x16 is 22 decimal and there are 22 bytes after the first byte before it then becomes all zeros.

**Comment by 8none1** [comment]
It's probably safe to assume that the two unknown numbers (0x02, 0x64) are the same as for grafitti mode. 

0x02 = steady
0x64 = speed

So the 0x02 value can probably be one of:
0x00 - flashing
0x01 - fade in and out
0x02 - solid on

**Comment by 8none1** [comment]
There is an experiment here which seems to do /something/:

https://github.com/8none1/idealLED/blob/c4a1eb86cb73b7694642fd3c43244a414afd9c25/idealled_controller.py#L96

**Comment by mas802** [comment]
Very nice, that seems to work. Interestingly for my strip (which is 50 leds) it looks like the first 50 are ignored. But if I do 25 colours and 4 leds each or if I prepend 50 and then do 2 leds for each it works well (with 24 colours). If I do more than 25 it goes into an effect mode.

**Comment by 8none1** [comment]
This looks like the Java code from the app:

```java
    public void sendDiyColor(BleDevice bleDevice, byte[] bArr, AgreementListener agreementListener) {
        int length;
        LogUtil.m104d("发送Diy数据：" + bArr.length);
        if (bArr.length % 99 == 0) {
            length = bArr.length / 99;
        } else {
            length = (bArr.length / 99) + 1;
        }
        byte[] bArr2 = {4, 68, 79, 79, 84, (byte) length, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        LogUtil.m104d("发送Diy数据命令：" + ByteUtils.BinaryToHexString(bArr2));
        byte[] encryptData = Agreement.getEncryptData(bArr2);
        this.dataMap.put(bleDevice, bArr);
        this.listenerMap.put(bleDevice, agreementListener);
        boolean write = BleManager.getInstance().write(bleDevice, encryptData);
        LogUtil.m104d("发送Diy数据结果 :" + write);
    }
```

**Comment by 8none1** [comment]
Which suggests that you can send up to 99 pixels in one go, if not then the 6th byte is used to indicate that there is more to come.

The two packets which are sent after the colour data seem fixed.  The last one does:
```java
    @Override // com.example.lightstrip.exposed.BleSendData
    public void setAllEnd(boolean z) {
        LightStripBleManager.getInstance().write1(Agreement.getEncryptData(new byte[]{8, 68, 84, 65, 82, 84, 67, 89, z ? (byte) 1 : (byte) 0, 0, 0, 0, 0, 0, 0, 0, 0}));
    }
```

So that seems to be a simple "I'm finished"

**Comment by 8none1** [comment]
Breakthrough!  

https://github.com/8none1/idealLED/blob/main/att_protocol.md#collections

**Comment by 8none1** [comment]
Ok, it works!

There are a couple of new functions to look at:

## Set the number of LEDs in the string

https://github.com/8none1/idealLED/blob/d09838ccfd72f2cbb0e9367438b2a262ab63a8b4/idealled_controller.py#L35

I don't know if this is why your string where acting funny, but maybe.  Anyway, it's definetly worth setting the correct number.

## Bulk custom pattern upload

The decoding of the protocol is documented here:  https://github.com/8none1/idealLED/blob/main/att_protocol.md#collections

and there is an example in the controller: 

https://github.com/8none1/idealLED/blob/d09838ccfd72f2cbb0e9367438b2a262ab63a8b4/idealled_controller.py#L116

There is the posibility of an optimisation where you have multiple pixels which are the same colour.  You don't have to upload data for each pixel, you can tell it that there are multiple pixels in one command.  This might shorten the number of bytes that need to be uploaded, and so might speed up the communication.

Please let me know how you get on, I'm really interested to see the effect you're bulding.

**Comment by mas802** [comment]
This is genius, I would never have figured all this out. Currently I am still struggling to get the timing right so the animation is not flickering, but still looks fluid. Not sure yet if I can achieve what I envisioned, but I for sure have to adapt my algorithm to the protocol to find the sweet spot. Might need some more tinkering, but I will sure post an update if I get it to work.
