### ISSUE TITLE
how can I contribute to add support for new LEDs? [not a programmer ;)]

### ISSUE THREAD

**Issue by pejotigrek** [8none1/idealLED#6]
Hi!

I've just bought some [16x16 BLE-controlled LED curtain](https://aliexpress.com/item/1005007315946442.html) that is managed by idealLED app. unfortunately, it's not recognized by the integration - it asks for device's MAC address, but when I enter this, and LEDs blink to confirm pairing - nothing else happens nor works. LEDs are not responding to on/off, colour or effect change etc.

I am not a programmer but I can follow directions [mostly ;)] so is there any way I could provide some logs or other data to make my curtains compatible with your integration, or it is too complex for a layman like myself?

**Comment by 8none1** [comment]
It's pretty complex I'm afraid.  Often manufacturers will change the Bluetooth protocol from model to model.  Sometimes they share components, like `On` & `Off` sometimes they change everything. 

The only real option is to decode it command by command as an entirely new protocol and that takes a while.

If you're interested in learning how there are a lot of resources on the web, but I highly recommend getting an nRF52840 dongle and installing the Sniffer software on it.  This will let you use Wireshark to help decode the bytes that are being sent by your phone to the lights.

It's quite an undertaking I'm afraid.

**Comment by pejotigrek** [comment]
fully understood, thanks!
