### ISSUE TITLE
since last Update no connection to booth Ideal LED possible

### ISSUE THREAD

**Issue by Nachgefragt** [8none1/idealLED#9]
as i wrote i had also no connection any more to my  two Ideal LED Christmas / Partlights.
![2024-11-17 19_13_02-Greenshot](https://github.com/user-attachments/assets/6aaded94-5798-4c45-a012-91fd0a3f86b6)

Could you help? Any idea what is reason for?

Thanks

**Comment by 8none1** [comment]
When did you update, and what did you update?  Was it all of HA or just the iDeal integration?

Do I understand correctly; things were working fine and then you updated and they broke?

Please can you:
 - Delete the device
 - Enable debugging
 - Try and add the device again
 - Turn off debugging again and attach the logs here?

**Comment by Nachgefragt** [comment]
I was a bluetooth problem by my side.
